name: Get next scheduled date

on:
  workflow_dispatch:

jobs:
  get_next_weekly_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@add-get-next-scheduled-date-workflow
    with:
      interval: weekly
      target_day: wednesday

  log_result:
    runs-on: ubuntu-latest
    needs: [get_next_weekly_scheduled_date]
    steps:
      - name: Log the next scheduled date
        run: |
          echo "The next weekly schedule date is: ${{ needs.get_next_weekly_scheduled_date.outputs.next_scheduled_date }}"
