name: Get next scheduled date

on:
  workflow_dispatch:

jobs:
  get_next_daily_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@feature
    with:
      interval: daily

  get_next_weekly_scheduled_date1:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@feature
    with:
      interval: weekly
      target_day: wednesday

  get_next_weekly_scheduled_date2:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@feature
    with:
      interval: weekly
      target_day: thursday

  get_next_weekly_scheduled_date3:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@feature
    with:
      interval: weekly
      target_day: tuesday

  log_result:
    runs-on: ubuntu-latest
    needs:
      - get_next_daily_scheduled_date
      - get_next_weekly_scheduled_date1
      - get_next_weekly_scheduled_date2
      - get_next_weekly_scheduled_date3
    steps:
      - name: Log the next scheduled date
        run: |
          cat <<EOF
          get_next_daily_scheduled_date: ${{ needs.get_next_daily_scheduled_date.outputs.next_scheduled_date }}
          get_next_weekly_scheduled_date1: ${{ needs.get_next_weekly_scheduled_date1.outputs.next_scheduled_date }}
          get_next_weekly_scheduled_date2: ${{ needs.get_next_weekly_scheduled_date2.outputs.next_scheduled_date }}
          get_next_weekly_scheduled_date3: ${{ needs.get_next_weekly_scheduled_date3.outputs.next_scheduled_date }}
          EOF
