name: Get next scheduled date

on:
  workflow_dispatch:

jobs:
  get_next_daily_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@tz-debug
    with:
      interval: daily
      time_zone: Pacific/Gambier # GMT-9

  get_next_weekly_scheduled_date1:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@tz-debug
    with:
      interval: weekly
      target_day: monday
      time_zone: Pacific/Gambier # GMT-9

  get_next_weekly_scheduled_date2:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@tz-debug
    with:
      interval: weekly
      target_day: tuesday
      time_zone: Pacific/Gambier # GMT-9

  get_next_weekly_scheduled_date3:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@tz-debug
    with:
      interval: weekly
      target_day: wednesday
      time_zone: Pacific/Gambier # GMT-9

  log_result:
    runs-on: ubuntu-latest
    needs:
      - get_next_daily_scheduled_date
      - get_next_weekly_scheduled_date1
      - get_next_weekly_scheduled_date2
      - get_next_weekly_scheduled_date3
    steps:
      - name: Log the next scheduled date
        run: |
          echo "inputs.time_zone: ${{ inputs.time_zone }}"
          echo "TZ: $TZ"
          date
          cat <<EOF
          It should be "2024/07/31". The actual value is ${{ needs.get_next_daily_scheduled_date.outputs.next_scheduled_date }}.
          It should be "2024/08/05". The actual value is ${{ needs.get_next_weekly_scheduled_date1.outputs.next_scheduled_date }}.
          It should be "2024/08/06". The actual value is ${{ needs.get_next_weekly_scheduled_date2.outputs.next_scheduled_date }}.
          It should be "2024/07/31". The actual value is ${{ needs.get_next_weekly_scheduled_date3.outputs.next_scheduled_date }}.
          EOF
