name: Create issue

on:
  # schedule:
  #   # 毎週水曜 13:00 JST に実行
  #   - cron: "0 4 * * wed"
  workflow_dispatch:

jobs:
  get_date:
    uses: route06/actions/.github/workflows/calc_next_date.yml@v2
    with:
      interval: weekly

  create_issue:
    needs: get_date
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: "${{ needs.get_date.outputs.next_date }} バグ報告"
          LABELS: "bug, documentation"
        with:
          filename: .github/workflows/templates/issue.md
      - run: |
          echo Created issue number ${{ steps.create-issue.outputs.number }}
          echo Created ${{ steps.create-issue.outputs.url }}
