name: Create issue

on:
  # schedule:
  #   # 毎週水曜 13:00 JST に実行
  #   - cron: "0 4 * * wed"
  workflow_dispatch:

jobs:
  # get_date:
  #   uses: route06/actions/.github/workflows/calc_next_date.yml@create-issue-workflow
  #   with:
  #     interval: weekly

  create_issue:
    # needs: get_date
    uses: route06/actions/.github/workflows/create_gh_issue.yml@create-issue-workflow
    with:
      title: Sample Issue
      description_template_path: .github/workflows/templates/issue.md
      # assignees: masutaka
      # labels: bug, wontfix
