name: Create issue

on:
  # schedule:
  #   # 毎週水曜 13:00 JST に実行
  #   - cron: "0 4 * * wed"
  workflow_dispatch:

jobs:
  get_date:
    uses: route06/actions/.github/workflows/calc_next_date.yml@v2
    with:
      interval: weekly

  create_issue:
    needs: get_date
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    timeout-minutes: 5
    env:
      TITLE: "${{ needs.get_date.outputs.next_date }} バグ報告2"
    steps:
      - uses: actions/checkout@v4
      - name: Setup issue template
        run: |
          echo '---' > hoge.md
          echo 'title: "${{ env.TITLE }}"' >> hoge.md

          echo '---' >> hoge.md
          echo  >> hoge.md

          cat .github/workflows/templates/issue.md >> hoge.md

      - name: debug1
        run: |
          ls -alF /tmp/
          cat hoge.md

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: hoge.md
      - name: debug2
        run: |
          echo Created ${{ steps.create-issue.outputs.url }}
