name: Create issue

on:
  # schedule:
  #   # 毎週水曜 13:00 JST に実行
  #   - cron: "0 4 * * wed"
  workflow_dispatch:

jobs:
  # get_date:
  #   uses: route06/actions/.github/workflows/calc_next_date.yml@create-issue-workflow
  #   with:
  #     interval: weekly

  get_date:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get this month
        run: |
          echo "THIS_MONTH=$(date +%Y/%m)" >> "$GITHUB_OUTPUT"
    outputs:
      this_month: ${{ env.THIS_MONTH }}

  create_issue:
    needs: get_date
    uses: route06/actions/.github/workflows/create_gh_issue.yml@create-issue-workflow
    permissions:
      contents: read
      issues: write
    with:
      title: ${{ needs.get_date.this_month }} Sample Issue
      description_template_path: .github/workflows/templates/issue.md
      # assignees: masutaka
      # labels: bug, wontfix
