name: Dependency Review

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency_review:
    uses: route06/actions/.github/workflows/dependency_review.yml@dependency_review-comment-summary-in-pr
