name: Trigger Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trigger_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            target:
              - .github/workflows/trigger.yml
              - hoge.txt
      - name: trigger
        if: steps.changes.outputs.target == 'true'
        run: echo 'triggered!'
